# 端口
server:
  port: 8081

#日志
logging:
  level:
    root: debug
  file:
    path: ./logs
    name: integratedManagementSystem.log


#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    druid:
      url: jdbc:mysql://127.0.0.1:3306/integratedManagementSystem?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: 0ZW?&PmZ
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true
  jpa:
    hibernate:
      #validate     加载hibernate时，验证创建数据库表结构
      #create       每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      #create-drop  加载hibernate时创建，退出时删除表结构
      #update       加载hibernate自动更新数据库结构
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
      roles: admin